language: objective-c
osx_image: xcode12.5

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCryptoWrapper.xcodeproj
    - IOS_SDK=iphonesimulator14.5
    - MACOS_SDK=macosx11.3
    - TVOS_SDK=appletvsimulator14.5
    - WATCHOS_SDK=watchsimulator7.4
    - CRYPTO_FRAMEWORK_NAME=VirgilCryptoWrapper
    - REPO=VirgilSecurity/virgil-cryptowrapper-x
    - REPO_PATH=https://github.com/VirgilSecurity/virgil-cryptowrapper-x.git
  matrix:
    - DESTINATION=""                                           PREFIX=""         SDK=""              BUILD="0"  PUBLISH_POD="YES"  PUBLISH_DOCS="YES"
    - DESTINATION="OS=14.5,name=iPhone 8"                      PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="arch=x86_64"                                PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=14.5,name=Apple TV"                      PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=7.4,name=Apple Watch Series 6 - 40mm"    PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_POD="NO"   PUBLISH_DOCS="NO"

before_install:
  - set -e
  - set -o pipefail

script:
  - carthage version
  - carthage bootstrap --use-xcframeworks

  - projs=( "VirgilCryptoFoundation" "VirgilCryptoPythia" "VirgilCryptoRatchet" )

  - |
    for proj in "${projs[@]}"; do
      SCHEME="${proj}_${PREFIX}"

      if [ $BUILD == "2" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
        # Run Tests
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      elif [ $BUILD == "1" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      fi
    done

  # Generate docs
  - if [[ $PUBLISH_DOCS == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
      ./CI/publish-docs.sh;
    fi

deploy:
  # Publish docs
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    local_dir: "docs"
    on:
      repo: $REPO
      branch: docs-automation
      tags: true
      condition: $PUBLISH_DOCS = "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+

  # Publish cocoapods
  - provider: script
    script: bash CI/publish-cocoapods.sh
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_POD == "YES" && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+
