language: swift
osx_image: xcode10.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=VirgilCryptoWrapper.xcodeproj
    - IOS_SDK=iphonesimulator12.1
    - MACOS_SDK=macosx10.14
    - TVOS_SDK=appletvsimulator12.1
    - WATCHOS_SDK=watchsimulator5.1
    - CRYPTO_FRAMEWORK_NAME=VirgilCryptoWrapper
    - REPO=VirgilSecurity/virgil-cryptowrapper-x
    - REPO_PATH=https://github.com/VirgilSecurity/virgil-cryptowrapper-x.git
  matrix:
    - DESTINATION=""                                         PREFIX=""         SDK=""              BUILD="0"  PUBLISH_CARTHAGE="YES"  PUBLISH_POD="YES"  PUBLISH_DOCS="YES"
    - DESTINATION="OS=12.1,name=iPhone SE"                   PREFIX="iOS"      SDK="$IOS_SDK"      BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="arch=x86_64"                              PREFIX="macOS"    SDK="$MACOS_SDK"    BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=12.1,name=Apple TV 4K"                 PREFIX="tvOS"     SDK="$TVOS_SDK"     BUILD="2"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"
    - DESTINATION="OS=5.1,name=Apple Watch Series 4 - 44mm"  PREFIX="watchOS"  SDK="$WATCHOS_SDK"  BUILD="1"  PUBLISH_CARTHAGE="NO"   PUBLISH_POD="NO"   PUBLISH_DOCS="NO"

before_install:
  - set -e
  - set -o pipefail

script:
  - carthage version
  - carthage bootstrap

  - projs=( "VirgilCryptoFoundation" "VirgilCryptoPythia" "VirgilCryptoRatchet" )

  - |
    for proj in "${projs[@]}"; do
      SCHEME="${proj}_${PREFIX}"

      if [ $BUILD == "2" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug clean build-for-testing | xcpretty;
        # Run Tests
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test-without-building | xcpretty;
      elif [ $BUILD == "1" ]; then
        # Build Framework
        xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release clean build | xcpretty;
      fi
    done

  # Build with carthage
  - if [ $PUBLISH_CARTHAGE == "YES" ]; then
      carthage build --no-skip-current;
      carthage archive;
      mv VirgilCryptoFoundation.framework.zip VirgilCryptoWrapper.framework.zip;
    fi

deploy:
  # Publish binary for Carthage
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    file:
      - "$CRYPTO_FRAMEWORK_NAME.framework.zip"
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_CARTHAGE = "YES"

  # Publish cocoapods
  - provider: script
    script: bash CI/publish-cocoapods.sh
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_POD == "YES" && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+

  # Upload docs to gh-pages
  - provider: script
    script: bash /CI/publish-docs.sh;
    skip_cleanup: true
    on:
      repo: $REPO
      tags: true
      condition: $PUBLISH_DOCS = "YES" && $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+