name: VirgilCrypto

options:
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  transitivelyLinkDependencies: true
  deploymentTarget:
    iOS: "10.0"
    watchOS: "4.0"
    tvOS: "10.0"
    macOS: "10.9"

targets:
  VirgilCryptoCommon:
    type: framework
    platform: [iOS, tvOS, macOS]
    scheme: {}
    info:
      path: VirgilCryptoCommon/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoCommon
    scheme:
      testTargets:
        - VirgilCryptoCommon-Tests_$platform
    sources:
      - VirgilCryptoCommon
    dependencies:
      - carthage: VSCCommon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoCommon

  VirgilCryptoCommon_watchOS:
    type: framework
    platform: [watchOS]
    scheme: {}
    info:
      path: VirgilCryptoCommon/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoCommon
    platformSuffix: ""
    sources:
      - VirgilCryptoCommon
    dependencies:
      - carthage: VSCCommon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoCommon
      PRODUCT_NAME: VirgilCryptoCommon

  VirgilCryptoCommon-Tests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS]
    scheme: {}
    sources:
      - VirgilCryptoCommonTests
    dependencies:
      - target: VirgilCryptoCommon_$platform

  VirgilCryptoFoundation:
    type: framework
    platform: [iOS, tvOS, macOS]
    scheme: {}
    info:
      path: VirgilCryptoFoundation/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoFoundation
    scheme:
      testTargets:
        - VirgilCryptoFoundation-Tests_$platform
    sources:
      - VirgilCryptoFoundation
    dependencies:
      - carthage: VSCFoundation
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoFoundation

  VirgilCryptoFoundation_watchOS:
    type: framework
    platform: [watchOS]
    scheme: {}
    info:
      path: VirgilCryptoFoundation/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoFoundation
    platformSuffix: ""
    sources:
      - VirgilCryptoFoundation
    dependencies:
      - carthage: VSCFoundation
    settings:
      PRODUCT_NAME: VirgilCryptoFoundation
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoFoundation

  VirgilCryptoFoundation-Tests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS]
    scheme: {}
    sources:
      - VirgilCryptoFoundationTests
    dependencies:
      - target: VirgilCryptoFoundation_$platform
      - carthage: VSCCommon

  VirgilCryptoPythia:
    type: framework
    platform: [iOS, tvOS, macOS]
    scheme: {}
    info:
      path: VirgilCryptoPythia/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoPythia
    scheme:
      testTargets:
        - VirgilCryptoPythia-Tests_$platform
    sources:
      - VirgilCryptoPythia
    dependencies:
      - carthage: VSCPythia
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoPythia

  VirgilCryptoPythia_watchOS:
    type: framework
    platform: [watchOS]
    scheme: {}
    info:
      path: VirgilCryptoPythia/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoPythia
    platformSuffix: ""
    sources:
      - VirgilCryptoPythia
    dependencies:
      - carthage: VSCPythia
    settings:
      PRODUCT_NAME: VirgilCryptoPythia
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoPythia

  VirgilCryptoPythia-Tests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS]
    scheme: {}
    sources:
      - VirgilCryptoPythiaTests
    dependencies:
      - target: VirgilCryptoPythia_$platform
      - carthage: VSCCommon

  VirgilCryptoRatchet:
    type: framework
    platform: [iOS, tvOS, macOS]
    scheme: {}
    info:
      path: VirgilCryptoRatchet/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoRatchet
    scheme:
      testTargets:
        - VirgilCryptoRatchet-Tests_$platform
    sources:
      - VirgilCryptoRatchet
    dependencies:
      - target: VirgilCryptoFoundation_$platform
      - carthage: VSCRatchet
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoRatchet

  VirgilCryptoRatchet_watchOS:
    type: framework
    platform: [watchOS]
    scheme: {}
    info:
      path: VirgilCryptoRatchet/Info.plist
      properties:
        CFBundleShortVersionString: 0.1.0
        CFBundleIdentitifer: com.virgilsecurity.VirgilCryptoRatchet
    platformSuffix: ""
    sources:
      - VirgilCryptoRatchet
    dependencies:
      - target: VirgilCryptoFoundation_$platform
      - carthage: VSCRatchet
    settings:
      PRODUCT_NAME: VirgilCryptoRatchet
      PRODUCT_BUNDLE_IDENTIFIER: com.virgilsecurity.VirgilCryptoRatchet

  VirgilCryptoRatchet-Tests:
    type: bundle.unit-test
    platform: [iOS, tvOS, macOS]
    scheme: {}
    sources:
      - VirgilCryptoRatchetTests
    dependencies:
      - target: VirgilCryptoRatchet_$platform
      - carthage: VSCCommon

aggregateTargets:
  Build_iOS:
    targets:
      - VirgilCryptoCommon_iOS
      - VirgilCryptoFoundation_iOS
      - VirgilCryptoPythia_iOS
      - VirgilCryptoRatchet_iOS

  Build_watchOS:
    targets:
      - VirgilCryptoCommon_watchOS
      - VirgilCryptoFoundation_watchOS
      - VirgilCryptoPythia_watchOS
      - VirgilCryptoRatchet_watchOS

  Build_tvOS:
    targets:
      - VirgilCryptoCommon_tvOS
      - VirgilCryptoFoundation_tvOS
      - VirgilCryptoPythia_tvOS
      - VirgilCryptoRatchet_tvOS

  Build_macOS:
    targets:
      - VirgilCryptoCommon_macOS
      - VirgilCryptoFoundation_macOS
      - VirgilCryptoPythia_macOS
      - VirgilCryptoRatchet_macOS

  Build_All:
    targets:
      - Build_iOS
      - Build_watchOS
      - Build_tvOS
      - Build_macOS
