name: check-swift-package-manager
on: [push]
jobs:
  check-swift-package-manager:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: swift --version
      - run: timeout 5m bash -c 'until swift build; do sleep 10; done'
      - run: swift test
