name: tests

on:
  push:
    branches:
      - develop
    pull_request:
      branches:
        - '*'

jobs:
  Tests:
    name: Tests
    runs-on: macOS-12
    env:
      PROJECT: VirgilCryptoWrapper.xcodeproj
    strategy:
      matrix:
        include:
          - destination: "OS=15.5,name=iPhone 13 Pro"
            prefix: "iOS"
            test: "1"
          - destination: "arch=x86_64"
            prefix: "macOS"
            test: "1"
          - destination: "OS=15.4,name=Apple TV"
            prefix: "tvOS"
            test: "1"
          - destination: "OS=8.5,name=Apple Watch Series 7 - 45mm"
            prefix: "watchOS"
            test: "0"
          - destination: "OS=9.0,name=Apple Watch Ultra - 49mm"
            prefix: "watchOS"
            test: "0"
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: actions/checkout@v2
      - name: Prepare Dependencies
        env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            carthage version
            carthage bootstrap --use-xcframeworks
      - name: Run ${{ matrix.prefix }} Tests
        run: |
            set -o pipefail
            projs=( "VirgilCryptoFoundation" "VirgilCryptoPythia" "VirgilCryptoRatchet" )

            for proj in "${projs[@]}"; do
                SCHEME="${proj}_${{ matrix.prefix }}"

                if [ "${{ matrix.test }}" == "1" ]; then
                    # Build Framework
                    xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Debug clean build-for-testing | xcpretty;
                    # Run Tests
                    xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Debug test-without-building | xcpretty;
                else
                    xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -destination "${{ matrix.destination }}" -configuration Release clean build | xcpretty;
                fi
            done
  SPM:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - run: brew install coreutils # install 'timeout' utility
      - run: swift --version
      - run: timeout 5m bash -c 'until swift build; do rm -fr .build && sleep 10; done' # fix for Swift Package Manager when it fails to download binary targets
      - run: swift test
