name: tests

on:
  push:
    branches:
      - master
      - git-actions
    pull_request:
      branches:
        - '*'

jobs:
  Tests
    name: Tests
    runs-on: macOS-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
      PROJECT: VirgilCryptoWrapper.xcodeproj
    strategy:
      matrix:
        include:
          - destination: "OS=15.5,name=iPhone 13 Pro"
            prefix: "iOS"
            sdk: "iphonesimulator15.5"
          - destination: "arch=x86_64"
            prefix: "macOS"
            sdk: "macosx12.4"
          - destination: "OS=15.5,name=Apple TV"
            prefix: "tvOS"
            sdk: "appletvsimulator15.5"
          - destination: "OS=8.5,name=Apple Watch Series 7 - 45mm"
            prefix: "watchOS"
            sdk: "watchsimulator8.5"
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Dependencies
        run: |
            carthage version
            carthage bootstrap --use-xcframeworks
      - name: Run ${{ matrix.prefix }} Tests
        run: |
            set -o pipefail
            projs=( "VirgilCryptoFoundation" "VirgilCryptoPythia" "VirgilCryptoRatchet" )

            for proj in "${projs[@]}"; do
                SCHEME="${proj}_${{ matrix.prefix }}"
                # Build Framework
                xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "${{ matrix.sdk }}" -destination "${{ matrix.destination }}" -configuration Debug clean build-for-testing | xcpretty;
                # Run Tests
                xcodebuild -verbose -project "$PROJECT" -scheme "$SCHEME" -sdk "${{ matrix.sdk }}" -destination "${{ matrix.destination }}" -configuration Debug test-without-building | xcpretty;
            done
  SPM:
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - run: brew install coreutils # install 'timeout' utility
      - run: swift --version
      - run: timeout 5m bash -c 'until swift build; do rm -fr .build && sleep 10; done' # fix for Swift Package Manager when it fails to download binary targets
      - run: swift test
